// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKIhT_1ftuAIXHXkuSG7nnR_VMYQ1g4v4',
    appId: '1:1056813042134:web:6519745b6d716bbd4abc77',
    messagingSenderId: '1056813042134',
    projectId: 'flutter-chat-8a468',
    authDomain: 'flutter-chat-8a468.firebaseapp.com',
    storageBucket: 'flutter-chat-8a468.appspot.com',
    measurementId: 'G-CHCS92W011',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW98lsQaiIJ3zOU_ZoilyeDXJefZjCBqI',
    appId: '1:1056813042134:android:71ad2cdbdf419f7f4abc77',
    messagingSenderId: '1056813042134',
    projectId: 'flutter-chat-8a468',
    storageBucket: 'flutter-chat-8a468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOm6YcaCOsDtOnEe5xj7c60cwzalcZA7k',
    appId: '1:1056813042134:ios:fa93b518aaf3f8db4abc77',
    messagingSenderId: '1056813042134',
    projectId: 'flutter-chat-8a468',
    storageBucket: 'flutter-chat-8a468.appspot.com',
    iosClientId: '1056813042134-1ev28h3nos12doeev317k1sedn2eb6oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOm6YcaCOsDtOnEe5xj7c60cwzalcZA7k',
    appId: '1:1056813042134:ios:fa93b518aaf3f8db4abc77',
    messagingSenderId: '1056813042134',
    projectId: 'flutter-chat-8a468',
    storageBucket: 'flutter-chat-8a468.appspot.com',
    iosClientId: '1056813042134-1ev28h3nos12doeev317k1sedn2eb6oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
